### PR TITLE
Fix backup of CloudInit secrets

### LINKED ISSUE #358: CloudInitNoCloud secrets (secretRef and networkDataSecretRef) are not backed up during VirtualMachine backups
**What happened**:
When backing up a VirtualMachine using the KubeVirt Velero plugin, Secrets referenced inside cloudInitNoCloud.secretRef and cloudInitNoCloud.networkDataSecretRef are not backed up. Only top-level volume.secret references are currently captured. As a result, important VM dependencies like SSH keys and network data configured via cloud-init can be missed during backup and restore.

**What you expected to happen**:
Secrets referenced by cloudInitNoCloud.secretRef and cloudInitNoCloud.networkDataSecretRef inside VM spec.template.spec.volumes should automatically be detected and backed up, just like normal volume.secret resources.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a Secret with cloud-init data.
- Create a VirtualMachine referencing that Secret via cloudInitNoCloud.secretRef.
- Backup the VM using Velero with the KubeVirt plugin.
- Observe that the Secret is not included in the backup.

**Additional context**:
The current plugin code (pkg/util/kvgraph/util.go:addVolumeGraph) handles Volume.Secret but does not process Volume.CloudInitNoCloud.SecretRef or Volume.CloudInitNoCloud.NetworkDataSecretRef. A small fix can be made to capture these cases during resource graph construction.

**Environment**:
- KubeVirt Velero Plugin Version: v0.7.1
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

[harvester-vm-manifest.txt](https://github.com/user-attachments/files/19940595/harvester-vm-manifest.txt)

### PR DESCRIPTION
**Pull request by sshende-catalogicsoftware**
- Add handling for cloudInitNoCloud.userDataSecretRef backup
- Add handling for cloudInitNoCloud.networkDataSecretRef backup
- Add handling for cloudInitConfigDrive.userDataSecretRef backup
- Add handling for cloudInitConfigDrive.networkDataSecretRef backup
- De-duplicate added dependent resources inside addVolumeGraph()
- Issue Reference: https://github.com/kubevirt/kubevirt-velero-plugin/issues/358

Fixes #358

### CODE REVIEW

File: pkg/util/kvgraph/util.go [hunk 1]
```diff
@@ -68,25 +68,57 @@ func addCommonVMIObjectGraph(spec v1.VirtualMachineInstanceSpec, vmName, namespa
 }
 
 func addVolumeGraph(vmiSpec v1.VirtualMachineInstanceSpec, vmName, namespace string, resources []velero.ResourceIdentifier) ([]velero.ResourceIdentifier, error) {
+	seen := make(map[string]struct{}) // Deduplication map
+
+	// Local wrapper: We need this since UserDataSecretRef and NetworkDataSecretRef may contain the same reference and we don;t want duplicates.
```
Comment (alromeros) [inline pkg/util/kvgraph/util.go:73]: We don't usually worry about duplicates since velero discards them if an object were backed up twice. Is there any reason for this?

Comment (ShellyKa13) [reply pkg/util/kvgraph/util.go:73]: Yep as @alromeros mentioned you can add the same object to the list and velero handles that for you.
So only need to add the new cases. Thanks

Comment (sseago) [reply pkg/util/kvgraph/util.go:73]: Within the internal velero item actions, there are cases which will always produce duplicates (returning VolumeSnapshotClass for each VolumeSnapshot, for example) -- this is fine. Velero maintains a map of items already handled, so it will skip items already backed up.

Comment (sshende-catalogicsoftware) [reply pkg/util/kvgraph/util.go:73]: No particular reason for removing duplicates apart from having to return unique ones. I'll remove the code for de-dupe and commit the change for review. Thank you.

Comment (sshende-catalogicsoftware) [reply pkg/util/kvgraph/util.go]: https://github.com/kubevirt/kubevirt-velero-plugin/pull/359/commits/2eced8dcffdc4b46e11b8bdd69e3abb3dc35ce1c

Implemented the suggestions in review comments.

**Comment by sshende-catalogicsoftware** [comment]
Can I squash and merge this PR?

File: pkg/util/kvgraph/util.go [hunk 2]
```diff
@@ -73,20 +73,40 @@ func addVolumeGraph(vmiSpec v1.VirtualMachineInstanceSpec, vmName, namespace str
...
+		case volume.CloudInitConfigDrive != nil:
+			if volume.CloudInitConfigDrive.UserDataSecretRef != nil {
+				resources = addVeleroResource(volume.CloudInitConfigDrive.UserDataSecretRef.Name, namespace, "secrets", resources)
+			}
+			if volume.CloudInitConfigDrive.NetworkDataSecretRef != nil {
+				resources = addVeleroResource(volume.CloudInitConfigDrive.NetworkDataSecretRef.Name, namespace, "secrets", resources)
+			}
 		}
 	}
-	// Returning full backup even if there was an error retrieving the backend PVC.
```
Comment (alromeros) [inline pkg/util/kvgraph/util.go:88]: Please don't remove this comment unless there's some reason related to the PR. This behavior still aplies.

**Review by alromeros — CHANGES_REQUESTED** [review]
Please squash the two commits into a single one to avoid having a second one that just removes stuff from the first. Other than that looks good, thanks!

File: pkg/util/kvgraph/util.go (hunk 2 above)
Comment (sshende-catalogicsoftware) [reply pkg/util/kvgraph/util.go:88]: Thanks.

- Squashed commits into one.
- Retained the comment that was unintentionally removed.

**Comment by sshende-catalogicsoftware** [comment]
Can I request for this PR be approved so that I can merge the change? Thank you.

File: pkg/util/kvgraph/util.go [hunk 3]
```diff
@@ -73,20 +73,42 @@ func addVolumeGraph(vmiSpec v1.VirtualMachineInstanceSpec, vmName, namespace str
...
+				resources = addVeleroResource(volume.CloudInitConfigDrive.UserDataSecretRef.Name, namespace, "secrets", resources)
+			}
+			if volume.CloudInitConfigDrive.NetworkDataSecretRef != nil {
+				resources = addVeleroResource(volume.CloudInitConfigDrive.NetworkDataSecretRef.Name, namespace, "secrets", resources)
+			}
 		}
 	}
 	// Returning full backup even if there was an error retrieving the backend PVC.
 	// The caller can decide wether to use the backup or handle the error.
+
```
Comment (alromeros) [inline pkg/util/kvgraph/util.go:111]: Just being nitpicky but these empty lines don't improve readability and I don't think are intentional. I'll approve and give chance to fix them. Thanks for the PR!
/approve

Comment (sshende-catalogicsoftware) [reply pkg/util/kvgraph/util.go:111]: Done. Thanks.

**Review by ShellyKa13 — COMMENTED** [review]
/lgtm
Thanks
